name: DGCAasks
channels:
  - conda-forge
dependencies:
  - python=3.10
  - graph-tool
  - tqdm
  - numpy
  - pandas  
  - pyarrow
  - scikit-learn
  - jsonpickle  
  - pip:
    - wrapt_timeout_decorator
    - multiset
